### ISSUE TITLE
Doesn't work on Netflix anymore

### ISSUE THREAD

**Issue by seanasy** [amarcu5/PiPer#26] opened 2017-09-18 01:07 UTC
The PiP icon is gone from the Netflix player for the past few weeks.

**Comment by amarcu5** [comment] 2017-09-18 11:45
Looks like this is another duplicate of issue #19 

Are you enrolled in Netflix's test participation? If so, you can try [opting out](http://showgoers.tv/test_opt_out.html)

**Comment by j4y4r1987** [comment] 2017-09-28 12:05
No longer working for me now as well. I'm not enrolled in their test participation.

**Comment by thatONEjustin** [comment] 2017-10-12 16:35
turned off test participation as well, still not working. is it not updated in the official safari extensions? uninstalling until confirmation.

**Comment by amarcu5** [comment] 2017-10-12 17:56
Safari Extension Gallery is a version behind at the time of writing (expecting approval shortly). If you’re willing to sacrifice auto updating you can get the latest stable version [here](https://raw.githubusercontent.com/amarcu5/PiPer/master/out/PiPer.safariextz).

**Comment by amarcu5** [comment] 2017-10-21 09:07
Safari Extension Gallery is now up to date.

**Closed by amarcu5** 2017-10-21 09:07 UTC
