### ISSUE TITLE
After MacOS 10.13.1 update button no longer works in netflix

### ISSUE THREAD

**Issue by mcreston** [amarcu5/PiPer#37] opened 2017-10-31 22:32 UTC
after i installed the new 10.13.1 update that was released today Piper no longer works in netflix.  the button shows up in it's normal place on the playback bar on netflix's site but when you click it nothing happens.

**Comment by cutsminmaxed** [comment] 2017-11-02 11:25
Confirmed the same thing started happening to me around the same timeframe.  I am on 10.2.6 however.  Only thing I can think of that changed on my end is I updated ublock origin from ~1.12 to 1.14.14, however I tried both separately whitelisting netflix and disabling the ublock origin extension and the problem persisted

**Comment by elfey** [comment] 2017-11-02 18:19
Confirmed, I have the same issue.

This is more than likely due to an update on Netflix's end if you are both running different OS versions and encountering the same problem.

**Comment by taharvey** [comment] 2017-11-03 03:25
Confirmed. Either on safari update, or netflix change. I'm on 10.12.6

**Comment by amarcu5** [comment] 2017-11-03 11:44
Thanks for the bug report all. Now fixed on the develop branch. acfb8b17daf5a299e53cfe24e56fc03c2bc2d7c2

Expect a Safari Extension Gallery update shortly

**Closed by amarcu5** 2017-11-03 11:44 UTC
Labels: bug
