### ISSUE TITLE
Netflix PiP icon disappeared 

### ISSUE THREAD

**Issue by mcreston** [amarcu5/PiPer#62] opened 2018-11-19 21:41 UTC
after using PiPer all morning on Netflix I came back from lunch to find the icon is missing on the Netflix playback UI and now the UI has changed entirely with PiPer nowhere to be found.

![screen shot 2018-11-19 at 1 41 02 pm](https://user-images.githubusercontent.com/30734497/48736705-d4d9d180-ec00-11e8-9a96-16829d5ab641.jpg)

**Comment by amarcu5** [comment] 2018-11-19 22:06
Thanks for the bug report. I've not been affected by the new UI - can you please check you're not enrolled in [test participation](https://www.netflix.com/donottest)?

**Comment by mcreston** [comment] 2018-11-19 22:09
just checked and I'm not enrolled in test participation

**Comment by mcreston** [comment] 2018-11-19 22:09
for whatever it's worth the plugin still works as it normally does on Amazon Prime video and all the other sites I've grown to love using it on.  so far it's a Netflix only thing

**Comment by amarcu5** [comment] 2018-11-19 22:42
Great, I'll keep my eye on this as it looks like the new UI might finally be rolling out. Fix is already done courtesy of @ximi (see pull request #56).

If all goes as planned could see this rolled into the next [big release](https://github.com/amarcu5/PiPer/tree/develop-1.0.0) hitting the Mac App Store and Chrome Web Store sometime next week.

**Comment by mcreston** [comment] 2018-11-19 22:47
that's great news!

**Comment by aDENTinTIME** [comment] 2018-11-23 21:40
Came to point out the Netflix issue as well, so glad this's being handled, thank you to all the people who work on this, it's fantastic!

**Comment by pieterdd** [comment] 2018-11-29 21:37
I see the new Netflix player now, so I can't use the button for the time being. Is releasing the fix the only bit of work that remains?

**Comment by amarcu5** [comment] 2018-12-02 01:40
This is now fixed and available in the big 1.0 release: get it now from the [Mac App Store](
https://itunes.apple.com/app/id1421915518?mt=12&ls=1) and [Chrome Web Store](
https://chrome.google.com/webstore/detail/piper/jbjleapidaddpbncgofepljddfeoghkc).

**Closed by amarcu5** 2018-12-02 01:40 UTC
Labels: bug

**Comment by pieterdd** [comment] 2018-12-02 09:15
Confirmed fixed, thank you!

**Comment by aDENTinTIME** [comment] 2018-12-03 07:47
Love the new dynamic icon, especially helpful for distinguishing from YouTube's miniplayer.
